heat_template_version: 2016-10-14
description: Django App server for   autoscaling demo
resources:  
  appserver:
    type: OS::Nova::Server
    properties:
      flavor: s2
      image: Ubuntucis-16IST
      key_name: k2
      availability_zone: nova      
      networks: 
          - port: {get_resource: app_net_port}      
      config_drive: True
      user_data: |           
            #!/bin/bash -v
            #change the proxy  for internal proxy , this is normally pre inserted inside the image 
            sudo sed -i "s/10\.172\.100\.14/10\.0\.0\.14/" /etc/apt/apt.conf
            sudo sed -i "s/3142/3128/" /etc/apt/apt.conf            
            sudo echo 'Acquire::https { Proxy "http://10.0.0.14:3128";};' >> /etc/apt/apt.conf
            echo 'http_proxy=http://10.0.0.14:3128/'|sudo tee -a  /etc/environment
            echo 'https_proxy=http://10.0.0.14:3128/'|sudo tee -a  /etc/environment
            sudo apt update            
            export DEBIAN_FRONTEND=noninteractive
            sudo -E apt-get -q -y install apache2 libapache2-mod-wsgi mysql-common git python-pip  python-mysqldb  mysql-client-core-5.7
            hip=$(sudo hostname -I)
            hname=$(sudo hostname)
            sudo echo $hip  $hname appserver |sudo tee -a /etc/hosts
            #change this later to get db ip automatically 
            sudo echo '70.0.0.11 dbhost' |sudo tee -a /etc/hosts
            sudo -E -H pip install --upgrade pip
            sudo -E -H pip install django psutil  mysqlclient
            sudo git clone https://github.com/BhujayKumarBhatta/djproject.git /opt
            cd /opt/djproject 
            python manage.py makemigrations simpleapp1 -noinput
            python manage.py migrate simpleapp1
            python manage.py migrate 
            echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin1', 'admin@example.com', 'welcome@123')" | python manage.py shell
            cat << 'EOL'| sudo tee -a  /etc/apache2/apache2.conf
            WSGIDaemonProcess djproject  threads=5  python-path=/opt/djproject
            WSGIScriptAlias / /opt/djproject/djproject/wsgi.py
            <Directory /opt/djproject/djproject>
                WSGIProcessGroup djproject
                WSGIApplicationGroup %{GLOBAL}
                AllowOverride all
                Order allow,deny
                Allow from all
                Require all granted
            </Directory>
            Alias /static/  /usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/
            <Directory /usr/local/lib/python2.7/dist-packages/django/contrib/admin/static/>
                Allow from all
                Require all granted
            </Directory>
            EOL     
            #sudo cp /opt/djproject/djproject/apache-conf/appserver.conf  /etc/apache2/sites-enabled/
            sudo service apache2 restart                         
                     
            
  app_net_port:
    type: OS::Neutron::Port
    properties:     
      network_id: c969c0e1-5dc8-48f4-ae3f-b550bd543c17
      fixed_ips:        
        - subnet_id: 46cb1f18-3430-42c6-ac78-75b04e9113dd
      security_groups: [ssh-ping,]         
      
  #assign a floating ip address to the load balancer  pool.
  app_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 0b21aa63-dfc7-4050-881e-12cc1b70b76c
      floating_subnet: 9504b136-4e82-4e8e-9981-32117af570e1     
      #port_id: {get_attr: [db, addresses, c969c0e1-5dc8-48f4-ae3f-b550bd543c17, 0, port]}
      port_id: { get_resource: app_net_port }   
  