heat_template_version: 2016-10-14
description: DB server for django-app  autoscaling demo
resources:  
  db:
    type: OS::Nova::Server
    properties:
      flavor: s2
      image: centos7ist
      key_name: k2
      availability_zone: nova
      security_groups: [ssh-ping,]      
      networks: [{network: c969c0e1-5dc8-48f4-ae3f-b550bd543c17},]
      user_data_format: RAW
      user_data: |        
            #!/bin/bash -v
            export DEBIAN_FRONTEND=noninteractive
            sudo -E apt-get -q -y install mysql-server
            sudo sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf
            #sudo sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/my.cnf             
            service mysql restart      
            cat << EOF | mysql -u root 
            CREATE DATABASE laptopdb;
            CREATE USER "monty"@"%"  IDENTIFIED BY "welcome@123";
            GRANT ALL PRIVILEGES ON laptopdb.* TO "monty"@"%"    IDENTIFIED BY "welcome@123";
            FLUSH PRIVILEGES;
            EXIT
            EOF
          